name: Docker Image CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag groovy-bot:$(date +%s)
